language: node_js
node_js:
- 4.3.2
cache:
  directories:
  - node_modules
  - $HOME/.npm

before_install:
- if [[ -n $TRAVIS_TAG ]]; then echo "Detect travis tag build, exit" && exit 0; fi # Exit if it is a Tag Build
- npm --version

install:
# Use update instead of npm install, so that we can benefit from local module cache
# - npm update --quiet --no-optional --depth=0
- npm install

before_script:
- export AWS_PROFILE=travis
- mkdir ~/.aws && touch ~/.aws/credentials # create .aws folder with placeholder credentials file
- echo '[profile travis]\nregion=eu-west-1' > ~/.aws/config # create .aws config file with default region

# Populate the credentials file by decrypting .secret-aws-travis / .secret-aws-travis-pullrequests
# When Travis initiated PR
- if [[ $TRAVIS_PULL_REQUEST =~ ^[0-9]+$ ]]; then openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET_PULLREQUESTS" -in ./.secret-aws-travis-pullrequests -out ~/.aws/credentials -d -a && echo "Using secret-aws-travis-pullrequests secrets."; fi
# When in Travis initiated branch build (master/alpha/prod)
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./.secret-aws-travis-branch -out ~/.aws/credentials -d -a && echo "Using secret-aws-travis-branch secrets."; fi

# For any Travis build, we need 'test' meta to run the tests
- echo '{}' > _meta/variables/s-variables-test.json && sls meta sync -s test -f >/dev/null

script:
- npm run build:docs
- npm test

after_success:
- pip install --user awscli

# Automated deployment to 'alpha' stage: Pull 'alpha' meta for an automated deployment
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then if [[ $TRAVIS_BRANCH == "alpha" ]]; then echo '{}' > _meta/variables/s-variables-alpha.json && sls meta sync -s alpha -f >/dev/null; fi fi;

# Automated deployment to 'prod' stage: Pull 'prod' meta for an automated deployment
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then if [[ $TRAVIS_BRANCH == "prod" ]]; then echo '{}' > _meta/variables/s-variables-prod.json && sls meta sync -s prod -f >/dev/null; fi fi;

# Current time
- d=$(date) && export CURRENT_TIMESTAMP="$d" && echo $CURRENT_TIMESTAMP

# Auto deploy to "test" stage on merges to master branch
- if [[ $TRAVIS_BRANCH == "master" ]]; then bash scripts/deployment/travis-autodeploy-stage-test.sh; fi;

# Auto deploy to "alpha" stage on alpha branch. Also tag the release.
- if [[ $TRAVIS_BRANCH == "alpha" ]]; then bash scripts/deployment/travis-autodeploy-stage-alpha.sh; fi;

# Auto deploy to "prod" stage on prod branch. Also tag the release.
- if [[ $TRAVIS_BRANCH == "prod" ]]; then bash scripts/deployment/travis-autodeploy-stage-prod.sh; fi;

env: # Dont touch this
  global:
  - TRAVIS_CI_SECRET_PULLREQUESTS=b7a2f8902a4c11675da3e1b421c6e28d95794fed
  - secure: oHzmcARbCvFobUZhcta11Wbw67NMDW9IXc7QyhbUG7utodbI+Dky7EJdLTZ1m7zpoucEJvR8K6MtAZnkEa0QRz87AqdcHGRZQt4MvwlmSxr4ea9QTyxb7fbmMfBfgWVCOdas3DWC9MQGeZylS1gAisAK7SpMLWRyEJIXFa6G5hqjoYdkZsxco4eE+Yq9n4CkUqlMBZ6ruX8oLuxqXK86sz5fKVjfh9BIsHwWaOPtRs+HyGnetawk0xCqk8ZAhGY7QO65jsy3m9HVvhbiINC8Ti0RSHgWRFDiCYSyQIy039+w0EgTuWStv4tk9K3V4S4Og22zT/tq1gGZoMZw6z+Ttm24eorr4kDMs3Wi2fNDT+32VAkyv/uR9Jp2J17UrSxSa6z1AtX/IAs/i231NVGaI/rmFsmyl9EuYDTbk184WEXnKXm/GGwxanbLW81EKPd1rIbO3zKhxCX3+2MBvr7k0/Dnxf1EFfTppdjz1z+tKbadzQnM/r4hy+DcIboKFit2ix+MBgJ7YPqDnf+MpD7nnLtYPXCmkXMzJ6CS3HP6HUo2slARm4w3cA70j0R8ntVeyrizQH/ddI6E7429Nyr3szEVXysW5iMqO4QvNKqJ7Jlq/LCp9ExAk79Gz3BXevonBQJEuXb3Nsx8psDSjGKjtGuHDxdO1+g14OOqgMkUWVY=
