language: node_js
node_js:
- 4.3.2
before_install:
- if [[ -n $TRAVIS_TAG ]]; then echo "Detect travis tag build, exit" && exit 0; fi # Exit if it is a Tag Build
- if [[ `npm -v` != 3.9.6* ]]; then npm i  -g npm@3.9.6; fi
- npm --version
before_script:
- export AWS_PROFILE=travis
- mkdir ~/.aws && touch ~/.aws/credentials # create .aws folder with placeholder credentials file
- echo '[profile travis]\nregion=eu-west-1' > ~/.aws/config # create .aws config file with default region

# populate credential file by decrypt .secret-aws-travis / .secret-aws-travis-pullrequests
- if [[ $TRAVIS_PULL_REQUEST =~ ^[0-9]+$ ]]; then openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET_PULLREQUESTS" -in ./.secret-aws-travis-pullrequests -out ~/.aws/credentials -d -a && echo "I ran"; fi # When travis run PR
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./.secret-aws-travis-branch -out ~/.aws/credentials -d -a && echo "I ran"; fi # When travis run branch

- sls function autoinstall -a

# get variable from s3 test file -> continuous deployment to test stage
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then if [[ $TRAVIS_BRANCH == "master" ]]; then echo '{}' > _meta/variables/s-variables-test.json && sls meta sync -s test -f; fi fi

# get variable from s3 alpha file -> alpha stage
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then if [[ $TRAVIS_BRANCH == "alpha" ]]; then echo '{}' > _meta/variables/s-variables-alpha.json && sls meta sync -s alpha -f; fi fi

# get variable from s3 test file -> for PRs
- if [[ $TRAVIS_PULL_REQUEST =~ ^[0-9]+$ ]]; then echo '{}' > _meta/variables/s-variables-test.json && sls meta sync -s test -f; fi

# no script for prod meta sync, as travis is not suppose to auto deploy prod



script:
- npm test
after_success:

# Current time
- d=$(date) && export CURRENT_TIMESTAMP="$d" && echo $CURRENT_TIMESTAMP

# Auto deploy to "test" stage on master branch
- bash scripts/deployment/travis-autodeploy-stage-test.sh

# Auto deploy to "alpha" stage on alpha branch with release tag
- bash scripts/deployment/travis-autodeploy-stage-alpha.sh
env: # Dont touch this
  global:
  - TRAVIS_CI_SECRET_PULLREQUESTS=b7a2f8902a4c11675da3e1b421c6e28d95794fed
  - secure: oHzmcARbCvFobUZhcta11Wbw67NMDW9IXc7QyhbUG7utodbI+Dky7EJdLTZ1m7zpoucEJvR8K6MtAZnkEa0QRz87AqdcHGRZQt4MvwlmSxr4ea9QTyxb7fbmMfBfgWVCOdas3DWC9MQGeZylS1gAisAK7SpMLWRyEJIXFa6G5hqjoYdkZsxco4eE+Yq9n4CkUqlMBZ6ruX8oLuxqXK86sz5fKVjfh9BIsHwWaOPtRs+HyGnetawk0xCqk8ZAhGY7QO65jsy3m9HVvhbiINC8Ti0RSHgWRFDiCYSyQIy039+w0EgTuWStv4tk9K3V4S4Og22zT/tq1gGZoMZw6z+Ttm24eorr4kDMs3Wi2fNDT+32VAkyv/uR9Jp2J17UrSxSa6z1AtX/IAs/i231NVGaI/rmFsmyl9EuYDTbk184WEXnKXm/GGwxanbLW81EKPd1rIbO3zKhxCX3+2MBvr7k0/Dnxf1EFfTppdjz1z+tKbadzQnM/r4hy+DcIboKFit2ix+MBgJ7YPqDnf+MpD7nnLtYPXCmkXMzJ6CS3HP6HUo2slARm4w3cA70j0R8ntVeyrizQH/ddI6E7429Nyr3szEVXysW5iMqO4QvNKqJ7Jlq/LCp9ExAk79Gz3BXevonBQJEuXb3Nsx8psDSjGKjtGuHDxdO1+g14OOqgMkUWVY=
  - secure: YZ5G3SqC6AkwRrGvQo2ofhazNc1EoBy4Wiv8VsLulJh4+3txujk8aZx7vCq3iFIFZiNKMWlGod+rJuKUhdqsHYk15kc8HgKYpimk7cCLCEh2PR2du2BWZvJ4Ky9+c0rccCkyZ305AIP3Uk2DvCC6beaS7N56TOz2KG+rT338hW8Miv0xL5Yrc2w6SEJn/mWZ2/0ba/hEcDsNK73kEqvx+HAue2hp/eKMwtj1qQCj0OupeBcnj+aleqgEbUa86QXKFZoqeHyCCIlEp/qNs23SnrwLw108UYqEmH23xt4T0MVK7I61pSQJLUmRlAp3+lcrYCWRhqOwkpF2AK4XqlOkSIYJGw2C3JUX1zec9yf9Wd8yEhfS7A263RDJZFucnm7zwfhtaffVSAh4WkrSDtIxBoCPDd+bK6j/3FyKPru6ooIz8ajXx1JYkkUIXCrUuegvIdiVFIA1pPmdJYSUkboeTksQFcsnZn6G3Urn/AtXlYXtcdiXwc2bW1pkuzB2CRUycg5q7Nq5GHooHtCls3xunl88BJ2kKVmT5w7T8gbepOurTEcUNc69GSad3ntCnqvUFera+lvlr9J1umj6wf5/K4HV8hR22J0Qc8QTZ1dTNPU1qtqQpLjjCL0BU0iQN1aZQjUuY3fEye+PCiokdRNeHo0nXIlSVv45oIUu0bJHhyE=
  - secure: eBP99wZ+dU6c6LXmVZT6XgLNWlQIoLt/38IhvRcnpIF4Q9J+UHmlnS0jNLC1t97fGboHT7jA2nPZjdhNQzUSNx8aYnPWQ9XJrlqAJTQe7PFzZDtas28uthMr9yfJOPa/47usZBL9Xv24ote13GdwIiyvfmpoZ+RZQ8qhPOL2O0mPht+jTB30E/pAbcNTYIAr/r/CKdi8UKpDpiLOHDvct/z1dLy01wWsTPl6abZN/6K/9NOxkEI5oxBZyw+YKS/jaOevDbGz/hwk1H9i0sEGNWAYdfnlY36LNWY9QVF27qMBDuUA6x+T3hpm0CNLqc4tOl6ztmwNsxp1He57bnxPzF/aCRmzkFgBw5WHtqcvi1Q4lL39JC9OO8I7ZhQndssLckMPJ8UVGCAiN2jop5T27dlIlWsOybMxzh9a85xfc82pLUWEAIeW6GeaG9JANrecZIFI4bqQbD2n4t1XA0by46GqTin2YzwcAqqQh1jiIEDtSrCe3S7psBbM9ckCn0BTOOYvHO1oUDv1P2942h7auZbLa/TN+uBVVrizY12JiU41j/GFrilKYsSLxdWQrsGiy0ToqiuqfzsRVZ/oRzdXFGYYtn16m8ziXpWLAJ43xjPMQgITYk8MNJv1bJGnRyiV44UUOIqrQlzb44dUrRx+nR/40cICXtk5xZiH0wELydU=
  - secure: AlmtSyd/GZisDetfGSOALVswEPjw5ffffFeBbgJiNKPoQF49JNavo8+iECdWuH9o2jjLRbD64dmDHZWtKDmn9epHBNHgMVIy2+Cb7mhsoYuhmaXw76/NxGugnDLZ4xx8pQZlMhUQCwLqlf/yPVbkrGRyXVyPn3obw7y1lPYVZY54JEI4FILS+Vhojp1TEzflJljF+jiodEf07WnLSJZdamiZMW/X+LV+kFumWZXe5Ri1MMRi4wWK5NXX+EDC5D8+hgxDO6O4vl0ca/puHeSLbL42NXwdYC3egjQJb0+cmls84BwbRovB7u2uPUcuMzuu5NOmEOF6wUU7RsXVOTdmq2x3V132TxfoHiXom05DmGbvKApZ4LnHNB4lbsvG0Ob/d9f2c+CGPFFLZwacFYjardY+soddnSkcTGtIx19d7mN8ucipnyqEXAzO2zixQ/53uhVzqD2sISEV4IIQrVJ7l4ak4v6Jg4WooscG5m6v8gliQm5oyu7z81X1DGAFIlbnDJK7vHk3wP5tRX+7s/hVohsTk+EiMGiLNJvXdw0Cg9OEWwaydTjshFwt0rU3r79t8tLSinVdJZBu9KNfo4gH8RQvgLQ/cx1LnNKua0NRhKkd+BfhfUcYR4xj3sEg23rFZOU20nEh9DZgjZeBht87wUopVjJ1Lj9QC92NjNoDIZI=
